### ISSUE TITLE
[BUG] 무적시간과 조작가능 시간에 차이가 없음

### ISSUE THREAD

**Issue by Arkru1204** [mirae-anet/Marchen#115]
---
# 1. 설명

무적시간(히트박스 off )과 조작 가능 시간과의 차이가 없어,
계속해서 피격 받는 상황이 오면 탈출 불가능 함

타임라인 예시)
(맞는다) - 히트박스 off, 조작 off - (지연) - 조작 on - (지연) - 히트박스 on - (끝)

**Comment by ramen4598** [comment]
GameScene : d8b66e16406ff258d14cebb226daef6e45f2f47a
