### ISSUE TITLE
농장에는 투쟁쥐 다 잡으면 건전지 나오게 하기

### ISSUE THREAD

**Issue by Arkru1204** [mirae-anet/Marchen#116]
일정 수를 넣고 다 잡으면 건전지가 특정 위치에 나오게

**Comment by ramen4598** [comment]
새로운 스폰너 만들기.

1. 하나의 스폰너에서 여러 마리의 에너미를 생성하는 방식 구현
2. 에너미의 스폰 위치는 일정한 범위 내에서 랜덤하게 생성
3. 에너미가 죽으면 스폰너의 카운트를 하나씩 추가
4. 카운터가 설정한 목표치에 도달하면 더이상 스폰하지 않고 사용자가 설정한 함수를 호출함.
5. 상속받아서 원하는 함수를 추가할 수 있게 작성.
