### ISSUE TITLE
밸런스 패치

### ISSUE THREAD

**Issue by ramen4598** [mirae-anet/Marchen#188]
- [ ] 1. 몬스터 버프 & 스폰되는 개체수 조절
- [x] 2. 플레이어 수에 따른 난이도 조절 [ 보스 몬스터 ] 
- [x] 3. 플레이어 수에 따른 난이도 조절 [ 카운트 스포너 ]  
- [ ] 3. 플레이어 너프
- [x] 4. 플레이어 리스폰 시간 너프

**Comment by ramen4598** [comment]
https://github.com/mirae-anet/Marchen/wiki/Marhen-%EB%B0%B8%EB%9F%B0%EC%8A%A4-%EC%8B%9C%ED%8A%B8

**Comment by ramen4598** [comment]
Runner.SessionInfo.PlayerCount and Runner.SessionInfo.MaxPlayers are valid only for matchmaking when you are looking into sessions from a Lobby.

On the Server, you can get the current Player count like this NetworkRunner.ActivePlayers.Count().



--

Ramon Melo

Photon Fusion Team

2번 참고

**Comment by pickup3415** [comment]
하트여왕 ( HeartQueenHPHandler ) 
- 플레이어 수에따라 HP 1000씩 증가

플레이어 리스폰 시간 너프 ( HPHandler ) 
- 2.5 > 10초
