### ISSUE TITLE
[bug] 일정 높이 이상에서 velocity.y 이상

### ISSUE THREAD

**Issue by Arkru1204** [mirae-anet/Marchen#28]
* y62 이상인 발판부터 점프해서 바닥으로 떨어지면 그라운드 체크가 안됨.
* if (Physics.BoxCast(feetpos, raySize / 2, Vector3.down, out RaycastHit rayHit, Quaternion.identity, 1f, LayerMask.GetMask("Ground"))) 부분 안됨
* y62 발판부터 서있는데 rigid.velocity.y 값이 0이 아님

**Comment by ramen4598** [comment]
확인 후 close 부탁 바람.

**Comment by ramen4598** [comment]
예토전생

**Comment by Arkru1204** [comment]
아마 확인한걸로는 가속도 붙고 빨라서 충돌 체크가 느려서 그럴거임
리지드바디랑 레이체크는 좀 안맞는듯..?
보간 설정이 들어가면 해결댐
