### ISSUE TITLE
[BUG] 죽으면 맵 아래로 떨어짐.

### ISSUE THREAD

**Issue by ramen4598** [mirae-anet/Marchen#38]
---
# 1. 설명

죽으면 맵을 뚫고 아래로 떨어짐.

아마 죽은 후에 rigidBody는 활성화되어 있는데 collider는가 꺼져서 그런듯.

죽으면 rigidBody도 비활성화 해야할 듯.

---

**Comment by Arkru1204** [comment]
pr에 넣어뒀는데, 죽으면 콜라이더는 끄면 안되고, 콜라이더가 들어가 있는 오브젝트의 레이어를 충돌 없는 레이어로 변경하면 됨(SuperArmor)

**Comment by ramen4598** [comment]
투명도를 활용하지 않고 rigidBody를 사용해서 해결함.
