### ISSUE TITLE
[BUG] .gitignore 디렉터리 위치 버그

### ISSUE THREAD

**Issue by ramen4598** [mirae-anet/Marchen#4]
---
# 1. 설명

.gitignore는 유니티 프로젝트 디렉터리 안에 위치해야 함.

현재 우리 .gitignore는 프로젝트 디렉터리와 동일한 디렉터리에 위치해서 동작하지 않는 버그가 있음.

해결 전까지는 절대 Push하지 말 것.

만나서 해결할 예정

**Comment by Kim-Yundong-KYD** [comment]
끝~!

**Comment by Kim-Yundong-KYD** [comment]
끝~!
