### ISSUE TITLE
게임 중에는 세션 참여 버튼 비활성화

### ISSUE THREAD

**Issue by ramen4598** [mirae-anet/Marchen#81]

**Comment by ramen4598** [comment]
이미 시작한 세션도 리스트에 표시되고 누르면 게임이 튕김.
이미 시작한 세션은 버튼을 누를 수 없도록 하거나 리스트에서 제외를 하고 바로 변경사항을 업데이트 해줘야 할 듯.

**Comment by pickup3415** [comment]
015433f9ee89146bb710e6fb6f7416feaddaf4e6

씬을 이동하면 게임중 UI 표시
